// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TypeDef } from '../golang/type-def.js';


export class ArrayType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ArrayType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsArrayType(bb:flatbuffers.ByteBuffer, obj?:ArrayType):ArrayType {
  return (obj || new ArrayType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsArrayType(bb:flatbuffers.ByteBuffer, obj?:ArrayType):ArrayType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ArrayType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

elem(obj?:TypeDef):TypeDef|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TypeDef()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

size():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startArrayType(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addElem(builder:flatbuffers.Builder, elemOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, elemOffset, 0);
}

static addSize(builder:flatbuffers.Builder, size:bigint) {
  builder.addFieldInt64(1, size, BigInt('0'));
}

static endArrayType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createArrayType(builder:flatbuffers.Builder, elemOffset:flatbuffers.Offset, size:bigint):flatbuffers.Offset {
  ArrayType.startArrayType(builder);
  ArrayType.addElem(builder, elemOffset);
  ArrayType.addSize(builder, size);
  return ArrayType.endArrayType(builder);
}
}
