// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { NodeValue } from '../golang/node-value.js';


export class BinaryNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BinaryNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsBinaryNode(bb:flatbuffers.ByteBuffer, obj?:BinaryNode):BinaryNode {
  return (obj || new BinaryNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsBinaryNode(bb:flatbuffers.ByteBuffer, obj?:BinaryNode):BinaryNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new BinaryNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

left(obj?:NodeValue):NodeValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NodeValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

right(obj?:NodeValue):NodeValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new NodeValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startBinaryNode(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLeft(builder:flatbuffers.Builder, leftOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, leftOffset, 0);
}

static addRight(builder:flatbuffers.Builder, rightOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, rightOffset, 0);
}

static endBinaryNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
