// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ChanDir } from '../golang/chan-dir.js';
import { TypeDef } from '../golang/type-def.js';


export class ChanType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChanType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChanType(bb:flatbuffers.ByteBuffer, obj?:ChanType):ChanType {
  return (obj || new ChanType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChanType(bb:flatbuffers.ByteBuffer, obj?:ChanType):ChanType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChanType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

elem(obj?:TypeDef):TypeDef|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TypeDef()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

dir():ChanDir {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ChanDir.Bidirectional;
}

static startChanType(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addElem(builder:flatbuffers.Builder, elemOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, elemOffset, 0);
}

static addDir(builder:flatbuffers.Builder, dir:ChanDir) {
  builder.addFieldInt8(1, dir, ChanDir.Bidirectional);
}

static endChanType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChanType(builder:flatbuffers.Builder, elemOffset:flatbuffers.Offset, dir:ChanDir):flatbuffers.Offset {
  ChanType.startChanType(builder);
  ChanType.addElem(builder, elemOffset);
  ChanType.addDir(builder, dir);
  return ChanType.endChanType(builder);
}
}
