// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Pair } from '../golang/pair.js';


export class FuncType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FuncType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFuncType(bb:flatbuffers.ByteBuffer, obj?:FuncType):FuncType {
  return (obj || new FuncType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFuncType(bb:flatbuffers.ByteBuffer, obj?:FuncType):FuncType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FuncType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

params(index: number, obj?:Pair):Pair|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Pair()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

paramsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

results(index: number, obj?:Pair):Pair|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Pair()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

resultsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

method(obj?:Pair):Pair|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Pair()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startFuncType(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addParams(builder:flatbuffers.Builder, paramsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, paramsOffset, 0);
}

static createParamsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startParamsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addResults(builder:flatbuffers.Builder, resultsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, resultsOffset, 0);
}

static createResultsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startResultsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMethod(builder:flatbuffers.Builder, methodOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, methodOffset, 0);
}

static endFuncType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
