// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { InterfaceMethod } from '../golang/interface-method.js';


export class InterfaceType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InterfaceType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInterfaceType(bb:flatbuffers.ByteBuffer, obj?:InterfaceType):InterfaceType {
  return (obj || new InterfaceType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInterfaceType(bb:flatbuffers.ByteBuffer, obj?:InterfaceType):InterfaceType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InterfaceType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

methods(index: number, obj?:InterfaceMethod):InterfaceMethod|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new InterfaceMethod()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

methodsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startInterfaceType(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMethods(builder:flatbuffers.Builder, methodsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, methodsOffset, 0);
}

static createMethodsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMethodsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endInterfaceType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInterfaceType(builder:flatbuffers.Builder, methodsOffset:flatbuffers.Offset):flatbuffers.Offset {
  InterfaceType.startInterfaceType(builder);
  InterfaceType.addMethods(builder, methodsOffset);
  return InterfaceType.endInterfaceType(builder);
}
}
