// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Kind {
  Nil = 0,
  Int = 1,
  Int8 = 2,
  Int16 = 3,
  Int32 = 4,
  Int64 = 5,
  Uint = 6,
  Uint8 = 7,
  Uint16 = 8,
  Uint32 = 9,
  Uint64 = 10,
  Uintptr = 11,
  Float32 = 12,
  Float64 = 13,
  Complex64 = 14,
  Complex128 = 15,
  String = 16,
  Rune = 17,
  Byte = 18,
  Boolean = 19,
  Pointer = 20,
  Struct = 21,
  Func = 22,
  Array = 23,
  Slice = 24,
  Map = 25,
  Channel = 26,
  Interface = 27
}
