// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TypeDef } from '../golang/type-def.js';


export class MapType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MapType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMapType(bb:flatbuffers.ByteBuffer, obj?:MapType):MapType {
  return (obj || new MapType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMapType(bb:flatbuffers.ByteBuffer, obj?:MapType):MapType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MapType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key(obj?:TypeDef):TypeDef|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TypeDef()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

value(obj?:TypeDef):TypeDef|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new TypeDef()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startMapType(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static endMapType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
