// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { BinaryNode } from '../golang/binary-node.js';
import { IndexedNode } from '../golang/indexed-node.js';
import { UnaryNode } from '../golang/unary-node.js';


export enum NodeUnion {
  NONE = 0,
  IndexedNode = 1,
  BinaryNode = 2,
  UnaryNode = 3
}

export function unionToNodeUnion(
  type: NodeUnion,
  accessor: (obj:BinaryNode|IndexedNode|UnaryNode) => BinaryNode|IndexedNode|UnaryNode|null
): BinaryNode|IndexedNode|UnaryNode|null {
  switch(NodeUnion[type]) {
    case 'NONE': return null; 
    case 'IndexedNode': return accessor(new IndexedNode())! as IndexedNode;
    case 'BinaryNode': return accessor(new BinaryNode())! as BinaryNode;
    case 'UnaryNode': return accessor(new UnaryNode())! as UnaryNode;
    default: return null;
  }
}

export function unionListToNodeUnion(
  type: NodeUnion, 
  accessor: (index: number, obj:BinaryNode|IndexedNode|UnaryNode) => BinaryNode|IndexedNode|UnaryNode|null, 
  index: number
): BinaryNode|IndexedNode|UnaryNode|null {
  switch(NodeUnion[type]) {
    case 'NONE': return null; 
    case 'IndexedNode': return accessor(index, new IndexedNode())! as IndexedNode;
    case 'BinaryNode': return accessor(index, new BinaryNode())! as BinaryNode;
    case 'UnaryNode': return accessor(index, new UnaryNode())! as UnaryNode;
    default: return null;
  }
}
