// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Flag } from '../golang/flag.js';
import { NodeUnion, unionToNodeUnion, unionListToNodeUnion } from '../golang/node-union.js';
import { Opcode } from '../golang/opcode.js';


export class Node {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Node {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNode(bb:flatbuffers.ByteBuffer, obj?:Node):Node {
  return (obj || new Node()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNode(bb:flatbuffers.ByteBuffer, obj?:Node):Node {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Node()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

opcode():Opcode {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : Opcode.Package;
}

parent():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

next():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

flags():Flag {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : Flag.None;
}

nodeType():NodeUnion {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : NodeUnion.NONE;
}

node<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startNode(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(0, id, BigInt('0'));
}

static addOpcode(builder:flatbuffers.Builder, opcode:Opcode) {
  builder.addFieldInt32(1, opcode, Opcode.Package);
}

static addParent(builder:flatbuffers.Builder, parent:bigint) {
  builder.addFieldInt64(2, parent, BigInt('0'));
}

static addNext(builder:flatbuffers.Builder, next:bigint) {
  builder.addFieldInt64(3, next, BigInt('0'));
}

static addFlags(builder:flatbuffers.Builder, flags:Flag) {
  builder.addFieldInt32(4, flags, Flag.None);
}

static addNodeType(builder:flatbuffers.Builder, nodeType:NodeUnion) {
  builder.addFieldInt8(5, nodeType, NodeUnion.NONE);
}

static addNode(builder:flatbuffers.Builder, nodeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, nodeOffset, 0);
}

static endNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNode(builder:flatbuffers.Builder, id:bigint, opcode:Opcode, parent:bigint, next:bigint, flags:Flag, nodeType:NodeUnion, nodeOffset:flatbuffers.Offset):flatbuffers.Offset {
  Node.startNode(builder);
  Node.addId(builder, id);
  Node.addOpcode(builder, opcode);
  Node.addParent(builder, parent);
  Node.addNext(builder, next);
  Node.addFlags(builder, flags);
  Node.addNodeType(builder, nodeType);
  Node.addNode(builder, nodeOffset);
  return Node.endNode(builder);
}
}
