// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Type, unionToType, unionListToType } from '../golang/type.js';


export class PointerType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PointerType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPointerType(bb:flatbuffers.ByteBuffer, obj?:PointerType):PointerType {
  return (obj || new PointerType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPointerType(bb:flatbuffers.ByteBuffer, obj?:PointerType):PointerType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PointerType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

elemType():Type {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Type.NONE;
}

elem<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startPointerType(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addElemType(builder:flatbuffers.Builder, elemType:Type) {
  builder.addFieldInt8(0, elemType, Type.NONE);
}

static addElem(builder:flatbuffers.Builder, elemOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, elemOffset, 0);
}

static endPointerType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPointerType(builder:flatbuffers.Builder, elemType:Type, elemOffset:flatbuffers.Offset):flatbuffers.Offset {
  PointerType.startPointerType(builder);
  PointerType.addElemType(builder, elemType);
  PointerType.addElem(builder, elemOffset);
  return PointerType.endPointerType(builder);
}
}
