// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { StructField } from '../golang/struct-field.js';


export class StructType {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StructType {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStructType(bb:flatbuffers.ByteBuffer, obj?:StructType):StructType {
  return (obj || new StructType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStructType(bb:flatbuffers.ByteBuffer, obj?:StructType):StructType {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StructType()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

fields(index: number, obj?:StructField):StructField|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new StructField()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fieldsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startStructType(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addFields(builder:flatbuffers.Builder, fieldsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, fieldsOffset, 0);
}

static createFieldsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFieldsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endStructType(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStructType(builder:flatbuffers.Builder, fieldsOffset:flatbuffers.Offset):flatbuffers.Offset {
  StructType.startStructType(builder);
  StructType.addFields(builder, fieldsOffset);
  return StructType.endStructType(builder);
}
}
