// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ArrayType } from '../golang/array-type.js';
import { ChanType } from '../golang/chan-type.js';
import { FuncType } from '../golang/func-type.js';
import { InterfaceType } from '../golang/interface-type.js';
import { MapType } from '../golang/map-type.js';
import { PointerType } from '../golang/pointer-type.js';
import { StructType } from '../golang/struct-type.js';


export enum Type {
  NONE = 0,
  PointerType = 1,
  InterfaceType = 2,
  StructType = 3,
  FuncType = 4,
  MapType = 5,
  ArrayType = 6,
  ChanType = 7
}

export function unionToType(
  type: Type,
  accessor: (obj:ArrayType|ChanType|FuncType|InterfaceType|MapType|PointerType|StructType) => ArrayType|ChanType|FuncType|InterfaceType|MapType|PointerType|StructType|null
): ArrayType|ChanType|FuncType|InterfaceType|MapType|PointerType|StructType|null {
  switch(Type[type]) {
    case 'NONE': return null; 
    case 'PointerType': return accessor(new PointerType())! as PointerType;
    case 'InterfaceType': return accessor(new InterfaceType())! as InterfaceType;
    case 'StructType': return accessor(new StructType())! as StructType;
    case 'FuncType': return accessor(new FuncType())! as FuncType;
    case 'MapType': return accessor(new MapType())! as MapType;
    case 'ArrayType': return accessor(new ArrayType())! as ArrayType;
    case 'ChanType': return accessor(new ChanType())! as ChanType;
    default: return null;
  }
}

export function unionListToType(
  type: Type, 
  accessor: (index: number, obj:ArrayType|ChanType|FuncType|InterfaceType|MapType|PointerType|StructType) => ArrayType|ChanType|FuncType|InterfaceType|MapType|PointerType|StructType|null, 
  index: number
): ArrayType|ChanType|FuncType|InterfaceType|MapType|PointerType|StructType|null {
  switch(Type[type]) {
    case 'NONE': return null; 
    case 'PointerType': return accessor(index, new PointerType())! as PointerType;
    case 'InterfaceType': return accessor(index, new InterfaceType())! as InterfaceType;
    case 'StructType': return accessor(index, new StructType())! as StructType;
    case 'FuncType': return accessor(index, new FuncType())! as FuncType;
    case 'MapType': return accessor(index, new MapType())! as MapType;
    case 'ArrayType': return accessor(index, new ArrayType())! as ArrayType;
    case 'ChanType': return accessor(index, new ChanType())! as ChanType;
    default: return null;
  }
}
