// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TypeDef } from '../golang/type-def.js';


export class TypeEntry {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TypeEntry {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTypeEntry(bb:flatbuffers.ByteBuffer, obj?:TypeEntry):TypeEntry {
  return (obj || new TypeEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTypeEntry(bb:flatbuffers.ByteBuffer, obj?:TypeEntry):TypeEntry {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TypeEntry()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

value(obj?:TypeDef):TypeDef|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new TypeDef()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startTypeEntry(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, key:number) {
  builder.addFieldInt32(0, key, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static endTypeEntry(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
