// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ValueFlag {
  None = 0,
  Pointer = 1,
  FuncMeta = 2,
  FuncParams = 4,
  FuncBody = 8,
  FuncResults = 16,
  PlaceHolder1 = 32,
  PlaceHolder2 = 64,
  PlaceHolder4 = 128,
  PlaceHolder5 = 256,
  PlaceHolder6 = 512
}
