// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ValueFlag {
  None = 0,
  Pointer = 1,
  Quotation = 2,
  IfConditon = 4,
  IfBody = 8,
  IfElse = 16,
  FuncMeta = 32,
  FuncParam = 64,
  FuncBody = 128,
  SwitchExp = 256,
  SwitchBody = 512,
  CaseExp = 1024,
  CaseBody = 2048,
  ForInit = 4096,
  ForCondition = 8192,
  ForPost = 16384,
  ForBody = 32768,
  ForRangeVar1 = 65536,
  ForRangeVar2 = 131072,
  ForRangeValue = 262144,
  DefaultBody = 524288
}
