// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { Type1 } from '../go/type1.js';
import { Type2 } from '../go/type2.js';
import { Type3 } from '../go/type3.js';


export enum NodeUnion {
  NONE = 0,
  Type1 = 1,
  Type2 = 2,
  Type3 = 3
}

export function unionToNodeUnion(
  type: NodeUnion,
  accessor: (obj:Type1|Type2|Type3) => Type1|Type2|Type3|null
): Type1|Type2|Type3|null {
  switch(NodeUnion[type]) {
    case 'NONE': return null; 
    case 'Type1': return accessor(new Type1())! as Type1;
    case 'Type2': return accessor(new Type2())! as Type2;
    case 'Type3': return accessor(new Type3())! as Type3;
    default: return null;
  }
}

export function unionListToNodeUnion(
  type: NodeUnion, 
  accessor: (index: number, obj:Type1|Type2|Type3) => Type1|Type2|Type3|null, 
  index: number
): Type1|Type2|Type3|null {
  switch(NodeUnion[type]) {
    case 'NONE': return null; 
    case 'Type1': return accessor(index, new Type1())! as Type1;
    case 'Type2': return accessor(index, new Type2())! as Type2;
    case 'Type3': return accessor(index, new Type3())! as Type3;
    default: return null;
  }
}
