// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { NodeValue } from '../go/node-value.js';


export class Type3 {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Type3 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsType3(bb:flatbuffers.ByteBuffer, obj?:Type3):Type3 {
  return (obj || new Type3()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsType3(bb:flatbuffers.ByteBuffer, obj?:Type3):Type3 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Type3()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value(obj?:NodeValue):NodeValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NodeValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startType3(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valueOffset, 0);
}

static endType3(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createType3(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  Type3.startType3(builder);
  Type3.addValue(builder, valueOffset);
  return Type3.endType3(builder);
}
}
