// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Type, unionToType, unionListToType } from '../program/type.js';


export class InterfaceMethod {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InterfaceMethod {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInterfaceMethod(bb:flatbuffers.ByteBuffer, obj?:InterfaceMethod):InterfaceMethod {
  return (obj || new InterfaceMethod()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInterfaceMethod(bb:flatbuffers.ByteBuffer, obj?:InterfaceMethod):InterfaceMethod {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InterfaceMethod()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

funcType():Type {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Type.NONE;
}

func<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startInterfaceMethod(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addFuncType(builder:flatbuffers.Builder, funcType:Type) {
  builder.addFieldInt8(1, funcType, Type.NONE);
}

static addFunc(builder:flatbuffers.Builder, funcOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, funcOffset, 0);
}

static endInterfaceMethod(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInterfaceMethod(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, funcType:Type, funcOffset:flatbuffers.Offset):flatbuffers.Offset {
  InterfaceMethod.startInterfaceMethod(builder);
  InterfaceMethod.addName(builder, nameOffset);
  InterfaceMethod.addFuncType(builder, funcType);
  InterfaceMethod.addFunc(builder, funcOffset);
  return InterfaceMethod.endInterfaceMethod(builder);
}
}
