// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Type, unionToType, unionListToType } from '../program/type.js';


export class TypeDef {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TypeDef {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTypeDef(bb:flatbuffers.ByteBuffer, obj?:TypeDef):TypeDef {
  return (obj || new TypeDef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTypeDef(bb:flatbuffers.ByteBuffer, obj?:TypeDef):TypeDef {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TypeDef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

base():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

typeType():Type {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Type.NONE;
}

type<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startTypeDef(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addBase(builder:flatbuffers.Builder, base:number) {
  builder.addFieldInt32(0, base, 0);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, idOffset, 0);
}

static addTypeType(builder:flatbuffers.Builder, typeType:Type) {
  builder.addFieldInt8(2, typeType, Type.NONE);
}

static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, typeOffset, 0);
}

static endTypeDef(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTypeDef(builder:flatbuffers.Builder, base:number, idOffset:flatbuffers.Offset, typeType:Type, typeOffset:flatbuffers.Offset):flatbuffers.Offset {
  TypeDef.startTypeDef(builder);
  TypeDef.addBase(builder, base);
  TypeDef.addId(builder, idOffset);
  TypeDef.addTypeType(builder, typeType);
  TypeDef.addType(builder, typeOffset);
  return TypeDef.endTypeDef(builder);
}
}
