// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { NodeValue } from '../program/node-value.js';


export class UnaryNode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnaryNode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnaryNode(bb:flatbuffers.ByteBuffer, obj?:UnaryNode):UnaryNode {
  return (obj || new UnaryNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnaryNode(bb:flatbuffers.ByteBuffer, obj?:UnaryNode):UnaryNode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnaryNode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value(obj?:NodeValue):NodeValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NodeValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startUnaryNode(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valueOffset, 0);
}

static endUnaryNode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnaryNode(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  UnaryNode.startUnaryNode(builder);
  UnaryNode.addValue(builder, valueOffset);
  return UnaryNode.endUnaryNode(builder);
}
}
