// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Flag } from './go/flag.js';
export { Node } from './go/node.js';
export { NodeUnion } from './go/node-union.js';
export { NodeValue } from './go/node-value.js';
export { Opcode } from './go/opcode.js';
export { Program } from './go/program.js';
export { Type1 } from './go/type1.js';
export { Type2 } from './go/type2.js';
export { Type3 } from './go/type3.js';
export { ValueFlag } from './go/value-flag.js';
